on: [ push, pull_request ]
name: tests
jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dart action
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - name: Install dependencies
        run: dart pub get
      - name: Wait for apt locks
        run: |
          while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1 || sudo fuser /var/lib/apt/lists/lock >/dev/null 2>&1 || sudo fuser /var/cache/apt/archives/lock >/dev/null 2>&1; do
            echo 'Waiting for apt...'
            sleep 1
          done
      - name: Pre-install Playwright browsers
        run: dart run tool/install_browsers.dart
      - name: Run tests & test coverage
        run: |
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
